settings:
  cctv_info:
    streaming_url: rtsp://163.239.27.189:8554/video1s1
    cam_id: 1
    streaming_type: test
  communication_info:
    server_url:
      ip: ${SERVER_ADDR}
      port: 8000
  decode_option:
    fps: 20
  model:
    object_detection:
      model_name: yolov4-416
      score_threshold: 0.1
      nms_threshold: 0.5
    tracker:
      tracker_names:
        - byte_tracker
        - sort_tracker
      byte_tracker:
        score_threshold: 0.1
        track_threshold: 0.5
        track_buffer: 30
        match_threshold: 0.8
        min_box_area: 10
        frame_rate: 20
      sort_tracker:
        score_threshold: 0.5
        max_age: 2
        min_hits: 3
    event:
      event_names:
      - assault
      - falldown
      - kidnapping
      - tailing
      - wanderer
      event_options:
        assault:
          score_threshold: 0.1
          tracker: byte_tracker
        falldown:
          score_threshold: 0.5
          tracker: none
        kidnapping:
          score_threshold: 0.5
          tracker: none
        tailing:
          score_threshold: 0.1
          tracker: byte_tracker
        wanderer:
          score_threshold: 0.1
          tracker: sort_tracker
